menu:
  Home: /
  Archives: /archives

widgets:
- search
- recent_posts
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: stueth
  show_replies: false
  tweet_count: 3
  widget_id: 411983651094536192
  follow_button: true
  show_follower_count: false

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: disqus
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light